# Use an official Node.js runtime as the base image
FROM node:18-alpine

# Create app directory
WORKDIR /app

# Install app dependencies
COPY package*.json ./

# Install global dependencies for TypeScript
RUN npm install -g typescript

# Install app dependencies
RUN npm install

# Copy the rest of the app source
COPY . .

# Compile TypeScript code
RUN tsc

# Make port 5000 available to the world outside this container
EXPOSE 3000

# Run app when the container launches
CMD ["npm", "start"]